export const GAME_CONFIG = {
  acceleration: 0.12,
  boostMultiplier: 1.45,
  brakeDrag: 2.4,
  carSpeed: 4.6,
  checkpointDistance: 320,
  checkpointNitroReward: 0.25,
  initialSpeed: 18,
  introMessage: 'PRESS ENTER TO DRIVE',
  maxSpeed: 42,
  maxNitro: 1,
  minSpeed: 12,
  nitroDrainRate: 0.32,
  nitroPickupReward: 0.35,
  nitroRechargeRate: 0.08,
  roadLimit: 2.5,
  spawnIntervalMs: 1100,
  totalCheckpoints: 3,
};
